dataset: Caltech101

encoder_dim:
  - [ 4096, 1024, 1024, 1024, 128 ]
  - [ 4096, 1024, 1024, 1024, 128 ]

n_classes: 101

batch_size: 1024
momentum: 0.98
temperature: 0.5

blr: 5.0e-4
min_blr: 5.0e-4
weight_decay: 0
data_path: data/multiview
output_dir: DIVIDE
seed: 1